POST https://localhost:7262/api/auth/register
Content-Type: application/json

{
  "email": "seller@test.com",
  "password": "123456",
  "role": "Seller"
}

###

POST https://localhost:7262/api/auth/login
Content-Type: application/json

{
  "email": "seller@test.com",
  "password": "123456"
}

###

POST https://localhost:7262/api/auth/forgot-password
Content-Type: application/json

{
  "email": "seller@test.com"
}

###

POST https://localhost:7262/api/auth/reset-password
Content-Type: application/json

{
  "email": "seller@test.com",
  "resetToken": "BURAYA_FORGOT_PASSWORD_CEVABINDAKI_TOKEN_GELECEK",
  "newPassword": "654321"
}

###

POST https://localhost:7262/api/auth/login
Content-Type: application/json

{
  "email": "seller@test.com",
  "password": "654321"
}

###

POST https://localhost:7262/api/auctionitems
Content-Type: application/json

{
  "title": "Used laptop",
  "description": "Laptop in working condition.",
  "category": "Laptop",
  "startingPrice": 5000,
  "auctionEndDate": "2026-06-07T18:00:00Z",
  "sellerId": 1
}

###

GET https://localhost:7262/api/auctionitems?category=Laptop

###

POST https://localhost:7262/api/devicephotos/detect
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="UserId"

1
--boundary
Content-Disposition: form-data; name="Photo"; filename="laptop.png"
Content-Type: image/png

< C:\Temp\laptop.png
--boundary--

###

GET https://localhost:7262/api/devicephotos/1/report